# Generated by Django 5.0.14 on 2026-07-29 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiModelRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                ("model_type", models.CharField(max_length=50)),
                ("version", models.CharField(default="v1.0.0", max_length=20)),
                ("framework", models.CharField(default="ONNX", max_length=50)),
                (
                    "weights_file_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="AiHealthRiskAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "overall_risk",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        db_index=True,
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("overall_risk_score", models.FloatField(default=0.15)),
                ("disease_risk_score", models.FloatField(default=0.1)),
                ("obesity_risk_score", models.FloatField(default=0.2)),
                ("activity_risk_score", models.FloatField(default=0.12)),
                ("risk_factors", models.JSONField(default=list)),
                ("recommendations", models.JSONField(default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessments",
                        to="pets.pet",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AiModelAbTestConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("test_name", models.CharField(max_length=100, unique=True)),
                ("candidate_traffic_percentage", models.IntegerField(default=20)),
                ("is_shadow_mode", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("accuracy_control", models.FloatField(default=0.92)),
                ("accuracy_candidate", models.FloatField(default=0.95)),
                ("latency_avg_ms_control", models.IntegerField(default=115)),
                ("latency_avg_ms_candidate", models.IntegerField(default=85)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidate_ab_tests",
                        to="ai_scan.aimodelregistry",
                    ),
                ),
                (
                    "control_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="control_ab_tests",
                        to="ai_scan.aimodelregistry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AiInferenceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("input_type", models.CharField(max_length=50)),
                ("execution_time_ms", models.IntegerField()),
                ("status", models.CharField(default="SUCCESS", max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai_scan.aimodelregistry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AiScanResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "scan_mode",
                    models.CharField(
                        choices=[
                            ("skin_disease", "Skin Disease Detection"),
                            ("eye_disease", "Eye Disease Detection"),
                            ("ear_infection", "Ear Infection Detection"),
                            ("dental_disease", "Dental Disease Detection"),
                            ("tick_detection", "Tick Detection"),
                            ("wound_detection", "Wound Detection"),
                            ("body_condition", "Body Condition Score"),
                        ],
                        db_index=True,
                        default="skin_disease",
                        max_length=30,
                    ),
                ),
                ("image_url", models.URLField(max_length=500)),
                (
                    "annotated_image_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("primary_diagnosis", models.CharField(db_index=True, max_length=200)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low Risk"),
                            ("MEDIUM", "Medium Risk"),
                            ("HIGH", "High Risk"),
                            ("CRITICAL", "Critical Risk"),
                        ],
                        default="LOW",
                        max_length=20,
                    ),
                ),
                ("diagnostic_summary", models.TextField()),
                (
                    "medical_disclaimer",
                    models.TextField(
                        default="AI diagnosis is for triage guidance only. Consult a licensed veterinarian."
                    ),
                ),
                ("bounding_boxes", models.JSONField(blank=True, default=list)),
                ("processing_time_ms", models.IntegerField(default=120)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_scans",
                        to="pets.pet",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
