# Generated by Django 5.0.14 on 2026-07-29 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SmartCollarDeviceStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                (
                    "device_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "mac_address",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("firmware_version", models.CharField(default="v1.0.0", max_length=30)),
                ("battery_percentage", models.IntegerField(default=100)),
                ("current_latitude", models.FloatField(default=0.0)),
                ("current_longitude", models.FloatField(default=0.0)),
                ("current_heart_rate", models.IntegerField(default=0)),
                ("current_temperature", models.FloatField(default=98.6)),
                ("rssi_dbm", models.IntegerField(default=-65)),
                ("is_online", models.BooleanField(db_index=True, default=True)),
                ("connection_count", models.IntegerField(default=1)),
                (
                    "last_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("is_geofence_active", models.BooleanField(default=True)),
                ("geofence_radius_meters", models.FloatField(default=150.0)),
                ("geofence_center_lat", models.FloatField(default=0.0)),
                ("geofence_center_lon", models.FloatField(default=0.0)),
                ("last_seen_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "current_pet",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="smart_collar",
                        to="pets.pet",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartCollarGeofenceEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ENTRY", "Geofence Entry"),
                            ("EXIT", "Geofence Exit"),
                            ("SOS", "Emergency SOS Triggered"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "collar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_events",
                        to="smart_collar.smartcollardevicestatus",
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="geofence_events",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SmartCollarOtaRollbackLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("attempted_version", models.CharField(max_length=30)),
                ("rolled_back_to_version", models.CharField(max_length=30)),
                ("rollback_reason", models.TextField()),
                ("rollback_status", models.CharField(default="SUCCESS", max_length=20)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "collar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ota_rollbacks",
                        to="smart_collar.smartcollardevicestatus",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SmartCollarPairingHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pairing_method",
                    models.CharField(
                        choices=[
                            ("BLE", "Bluetooth Low Energy"),
                            ("QR", "QR Code Scan"),
                            ("MANUAL", "Manual Input"),
                        ],
                        default="BLE",
                        max_length=20,
                    ),
                ),
                (
                    "pairing_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("UNPAIRED", "Unpaired"),
                            ("REPLACED", "Replaced"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("paired_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("unpaired_at", models.DateTimeField(blank=True, null=True)),
                (
                    "collar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairing_history",
                        to="smart_collar.smartcollardevicestatus",
                    ),
                ),
                (
                    "paired_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collar_history",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "ordering": ["-paired_at"],
            },
        ),
        migrations.CreateModel(
            name="SmartCollarSecurityProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("device_secret_hash", models.CharField(max_length=255)),
                (
                    "provisioning_key",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "device_auth_token_hash",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "device_certificate_thumbprint",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "device_status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("ACTIVE", "Active"),
                            ("BLOCKED", "Blocked"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="REGISTERED",
                        max_length=20,
                    ),
                ),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("last_authenticated_at", models.DateTimeField(blank=True, null=True)),
                ("secret_rotated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "firmware_min_compat_version",
                    models.CharField(default="v1.0.0", max_length=30),
                ),
                (
                    "collar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_profile",
                        to="smart_collar.smartcollardevicestatus",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SmartCollarTelemetryHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("heart_rate_bpm", models.IntegerField()),
                ("respiratory_rate", models.IntegerField(default=24)),
                ("temperature_fahrenheit", models.FloatField()),
                ("steps_count", models.IntegerField(default=0)),
                ("sleep_hours", models.FloatField(default=0.0)),
                ("activity_level", models.CharField(default="Resting", max_length=50)),
                ("battery_percentage", models.IntegerField()),
                ("rssi_dbm", models.IntegerField()),
                ("is_sos_triggered", models.BooleanField(db_index=True, default=False)),
                (
                    "collar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_logs",
                        to="smart_collar.smartcollardevicestatus",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collar_telemetry",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telemetry_logs",
                        to="pets.pet",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["pet", "-timestamp"],
                        name="smart_colla_pet_id_d9377d_idx",
                    ),
                    models.Index(
                        fields=["collar", "-timestamp"],
                        name="smart_colla_collar__a542f7_idx",
                    ),
                    models.Index(
                        fields=["owner", "-timestamp"],
                        name="smart_colla_owner_i_92b98d_idx",
                    ),
                    models.Index(
                        fields=["is_sos_triggered", "-timestamp"],
                        name="smart_colla_is_sos__40de53_idx",
                    ),
                ],
            },
        ),
    ]
