# Generated by Django 5.0.14 on 2026-07-29 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthPassportRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("title", models.CharField(db_index=True, max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("vaccination", "Vaccination Record"),
                            ("medical_history", "Medical History"),
                            ("diagnosis", "Diagnosis"),
                            ("treatment", "Treatment"),
                            ("prescription", "Prescription"),
                            ("surgery", "Surgery"),
                            ("allergy", "Allergy"),
                            ("lab_report", "Lab Report"),
                            ("deworming", "Deworming"),
                            ("tick_prevention", "Tick & Flea Prevention"),
                            ("vet_note", "Veterinarian Note"),
                        ],
                        db_index=True,
                        default="vaccination",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "clinic_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("date_administered", models.DateField(db_index=True)),
                ("date_expiration", models.DateField(blank=True, null=True)),
                ("is_verified_ehr", models.BooleanField(db_index=True, default=True)),
                (
                    "document_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_records",
                        to="pets.pet",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "veterinarian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="signed_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_administered"],
                "indexes": [
                    models.Index(
                        fields=["pet", "type", "is_deleted"],
                        name="health_pass_pet_id_126ef5_idx",
                    )
                ],
            },
        ),
    ]
