# Generated by Django 5.0.14 on 2026-07-29 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("canine", "Canine (Dog)"),
                            ("feline", "Feline (Cat)"),
                            ("avian", "Avian (Bird)"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="canine",
                        max_length=20,
                    ),
                ),
                ("breed", models.CharField(db_index=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female")],
                        default="male",
                        max_length=10,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "weight_kg",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("color", models.CharField(blank=True, default="", max_length=50)),
                (
                    "noseprint_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "microchip_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("adoption_status", models.CharField(default="Owned", max_length=50)),
                (
                    "vaccination_status",
                    models.CharField(
                        choices=[
                            ("up_to_date", "Up to Date"),
                            ("due_soon", "Due Soon"),
                            ("overdue", "Overdue"),
                            ("unknown", "Unknown"),
                        ],
                        db_index=True,
                        default="up_to_date",
                        max_length=20,
                    ),
                ),
                ("is_sterilized", models.BooleanField(default=True)),
                (
                    "blood_group",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("allergies", models.TextField(blank=True, default="")),
                ("medical_notes", models.TextField(blank=True, default="")),
                (
                    "emergency_contact",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "profile_photo_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "qr_code_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_vet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "is_active", "is_deleted"],
                        name="pets_pet_owner_i_db5cd9_idx",
                    ),
                    models.Index(
                        fields=["species", "breed"], name="pets_pet_species_d5b52d_idx"
                    ),
                ],
            },
        ),
    ]
